runtime: php81 # Replace with php74 to use PHP 7.4

beta_settings:
    cloud_sql_instances: "mymovielistit390gmu:asia-east1:mymovielistit390gmu2"

env_variables:
    # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
    # values obtained when configuring your Cloud SQL instance.
    MYSQL_USER: 'root'
    MYSQL_PASSWORD: 'Zp@?V(<E#FD?6asI'
    MYSQL_DSN: 'mysql:dbname=DBNAME;unix_socket=/cloudsql/mymovielistit390gmu:asia-east1:mymovielistit390gmu2'

handlers:

- url: /css
  static_dir: css

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  
- url: /js
  static_dir: js

- url: /.*
  script: index.php


